// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zdsowhatfqvxkjvlcrjl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpkc293aGF0ZnF2eGtqdmxjcmpsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3NjgzNjYsImV4cCI6MjA1OTM0NDM2Nn0.qBdoyT8zTfSjRb5YLgYvdAz9yqFajI57NCT4XUMK6ZY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);